<template>
  <section class="bg-primary text-primary-foreground">
    <div class="container grid gap-6 py-16 md:gap-20 md:py-24 lg:grid-cols-2">
      <div class="flex flex-col gap-5">
        <p class="font-mono text-xs tracking-[0.08em] text-lime dark:text-primary-foreground md:text-[13px]">
          READ BEFORE YOU BUY
        </p>
        <h2>Evidence-based, not prescriptive.</h2>
      </div>
      <p class="text-base leading-relaxed md:pt-9 md:text-[19px]">
        Recommendations are generated by an AI model from your answers and a
        curated list of studied ingredients. Treat them as a starting point for
        a conversation with your doctor, not a replacement for one, especially
        if you have a condition or take medication.
      </p>
    </div>
  </section>
</template>
